/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-09-11 07:56:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sun.org.apache.xml.internal.security.utils.Base64;
import java.net.*;
import java.util.*;
import com.channel.dao.*;
import com.channel.dao.impl.*;
import com.channel.model.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write('\n');

	if (session.getAttribute("auth") == null) {
		response.sendRedirect("login.jsp");
	}
	ChannelDao dao = new ChannelDaoImpl();
	OfflineChannelDao offDao = new OfflineChannelDaoImpl();
	List<Channel> list = dao.queryAll();
	Iterator<Channel> it = list.iterator();

	List<String> offline = offDao.queryAllOfflineChannel();
	Iterator<String> itr = offline.iterator();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title>豌豆渠道后台</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("<meta name=\"keywords\" content=\"\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css\" />\n");
      out.write("<link href=\"static/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction encode(url) {\n");
      out.write("\t\treturn encodeURI(uri);\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("\tpadding-top: 40px;\n");
      out.write("\tpadding-bottom: 40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-signin {\n");
      out.write("\tmax-width: 300px;\n");
      out.write("\tpadding: 19px 29px 29px;\n");
      out.write("\tmargin: 0 auto 20px;\n");
      out.write("\tbackground-color: #fff;\n");
      out.write("\tborder: 1px solid #e5e5e5;\n");
      out.write("\t-webkit-border-radius: 5px;\n");
      out.write("\t-moz-border-radius: 5px;\n");
      out.write("\tborder-radius: 5px;\n");
      out.write("\t-webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);\n");
      out.write("\t-moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);\n");
      out.write("\tbox-shadow: 0 1px 2px rgba(0, 0, 0, .05);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-signin .form-signin-heading,.form-signin .checkbox {\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-signin input[type=\"text\"],.form-signin input[type=\"password\"] {\n");
      out.write("\tfont-size: 16px;\n");
      out.write("\theight: auto;\n");
      out.write("\tmargin-bottom: 15px;\n");
      out.write("\tpadding: 7px 9px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/common.css\">\n");
      out.write("<link href=\"static/css/bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\"\n");
      out.write("\thref=\"static/ico/apple-touch-icon-144-precomposed.png\">\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\"\n");
      out.write("\thref=\"static/ico/apple-touch-icon-114-precomposed.png\">\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\"\n");
      out.write("\thref=\"static/ico/apple-touch-icon-72-precomposed.png\">\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\n");
      out.write("\thref=\"static/ico/apple-touch-icon-57-precomposed.png\">\n");
      out.write("<link rel=\"shortcut icon\" href=\"static/ico/favicon.png\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"wrapper\"\n");
      out.write("\t\tclass=");
      out.print(session.getAttribute("auth") != null ? "" : "displayn");
      out.write(">\n");
      out.write("\t\t\n");
      out.write("\t\t<table id=\"channel-table\" class=\"bd table table-striped\">\n");
      out.write("\t\t\t<caption>\n");
      out.write("\t\t\t\t<b>P3推广后台</b>\n");
      out.write("\t\t\t\t<div style=\"float: right;\">\n");
      out.write("\t\t\t\t\tFrom: <input type=\"text\" id=\"from\"\n");
      out.write("\t\t\t\t\t\tname=\"from\" style=\"height: 14px;\" />  to: <input\n");
      out.write("\t\t\t\t\t\ttype=\"text\" id=\"to\" name=\"to\" style=\"height: 14px;\" />\n");
      out.write("\t\t\t\t\t<a id=\"import\" class=\"marginRT30\" style=\"font-size : 15px\">导出CSV<span id=\"loading\" style=\"height: 30px; width : 30px; float: right;\"><img style=\"height: 30px; width : 30px;\"/></span></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</caption>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<th>网盟编号</th>\n");
      out.write("\t\t\t\t<th>分类</th>\n");
      out.write("\t\t\t\t<th>对内后台</th>\n");
      out.write("\t\t\t\t<th colspan=\"2\">对外后台</th>\n");
      out.write("\t\t\t\t<th colspan=\"2\">备注&更多信息</th>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t");

				int i = 0;
				while (it.hasNext()) {
			
      out.write("<tr>\n");
      out.write("\t\t\t\t");

					Channel channel = it.next();
				
      out.write("\n");
      out.write("\t\t\t\t<td class=\"lt\">");
      out.print(++i);
      out.write("</td>\n");
      out.write("\t\t\t\t<td>");
      out.print(channel.getChannelType() == null ? "" : channel.getChannelType()  );
      out.write("</td>\n");
      out.write("\t\t\t\t<td><a class=\"channel-name\"\n");
      out.write("\t\t\t\t\thref=\"redirect?action=in&id=");
      out.print(channel.getId());
      out.write("&count=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(channel.getChannelName());
      out.write("</a>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td><a class=\"channel-url\"\n");
      out.write("\t\t\t\t\thref=\"redirect?action=");
      out.print(Base64.encode("out".getBytes()) );
      out.write("&id=");
      out.print(Base64.encode(String.valueOf(channel.getId()).getBytes()));
      out.write("&count=");
      out.print(Base64.encode(String.valueOf(i).getBytes()));
      out.write("\">对外后台</a>\n");
      out.write("\t\t\t\t\t");

						session.setAttribute("channelName" + i, channel.getChannelName());
					 
      out.write("\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td class=\"change\">变更链接</td>\n");
      out.write("\t\t\t\t<td class=\"edit\">编辑</td>\n");
      out.write("\t\t\t\t<td class=\"dele\">删除</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<div class=\"ft\">\n");
      out.write("\t\t\t<input type=\"text\" id=\"name\" name=\"name\" /> <label id=\"add\"\n");
      out.write("\t\t\t\tfor=\"name\" class=\"link\">增加网盟</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div id=\"\" style=\"width: 100px; margin-left: 5%;\">\n");
      out.write("\t\t<table id=\"channel-table\" class=\"bd table table-striped\">\n");
      out.write("\t\t\t<caption>\n");
      out.write("\t\t\t\t<b>已下线网盟</b>\n");
      out.write("\t\t\t</caption>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<th>网盟编号</th>\n");
      out.write("\t\t\t\t<th>网盟名称</th>\n");
      out.write("\t\t\t\t<th colspan=\"2\">操作</th>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\n");
      out.write("\t\t\t");

				int j = 0;
				while (itr.hasNext()) {
			
      out.write("<tr>\n");
      out.write("\t\t\t\t");

					String channelName = itr.next();
				
      out.write("\n");
      out.write("\t\t\t\t<td class=\"lt\">");
      out.print(++j);
      out.write("</td>\n");
      out.write("\t\t\t\t<td><a class=\"channel-name\"\n");
      out.write("\t\t\t\t\thref=\"offline_source.jsp?id=123&name=");
      out.print(channelName);
      out.write('"');
      out.write('>');
      out.print(channelName);
      out.write("</a></td>\n");
      out.write("\t\t\t\t<td ><a onclick=\"return confirm('确定删除渠道?')\" href=\"offline?action=del&channelName=");
      out.print(channelName);
      out.write("\">删除</a>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td><a href=\"offline?action=recover&channelName=");
      out.print(channelName);
      out.write("\">还原</a>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\n");
      out.write("\t\t</table>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"dele-Channel\">\n");
      out.write("\t\t<div class=\"mask\"></div>\n");
      out.write("\t\t<div id=\"dele-Channel-wrapper\" class=\"wrapper\">\n");
      out.write("\t\t\t<p>确定要删除这条渠道嘛？</p>\n");
      out.write("\t\t\t<br>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<button id=\"y-dele-btn\" type=\"button\">是的，我要删掉</button>\n");
      out.write("\t\t\t\t<button id=\"n-dele-btn\" type=\"button\">不，我不想删</button>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"edit-Channel\">\n");
      out.write("\t\t<div class=\"mask\"></div>\n");
      out.write("\t\t<form id=\"edit-Channel-wrapper\" class=\"wrapper\">\n");
      out.write("\t\t\t<p class=\"bold\">编辑渠道</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"channel_type\">渠道分类</label>\n");
      out.write("\t\t\t\t<input\n");
      out.write("\t\t\t\t\ttype=\"text\" id=\"channel_type\" name=\"channel_type\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"channelName\">渠道名称</label>\n");
      out.write("\t\t\t\t<input\n");
      out.write("\t\t\t\t\ttype=\"text\" id=\"channelName\" name=\"channelName\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"contact\">联系人</label> <input type=\"hidden\"\n");
      out.write("\t\t\t\t\tid=\"channel-name\" name=\"channel-name\" value=\"\" /> <input\n");
      out.write("\t\t\t\t\ttype=\"text\" id=\"contact\" name=\"contact\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"qq\">QQ</label> <input type=\"text\" id=\"qq\" name=\"qq\"\n");
      out.write("\t\t\t\t\tstyle=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"tel\">Tel</label> <input type=\"text\" id=\"tel\" name=\"tel\"\n");
      out.write("\t\t\t\t\tstyle=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"email\">Email</label> <input type=\"text\" id=\"email\"\n");
      out.write("\t\t\t\t\tname=\"email\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"address\">地址</label> <input type=\"text\" id=\"address\"\n");
      out.write("\t\t\t\t\tname=\"address\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"message\">备注</label> <input type=\"text\" id=\"comment\"\n");
      out.write("\t\t\t\t\t name=\"comment\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"progress\">财务流程</label> <input type=\"text\"\n");
      out.write("\t\t\t\t\tid=\"fin_process\" name=\"fin_process\"\n");
      out.write("\t\t\t\t\tstyle=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p class=\"bold\">财务信息</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"title\">抬头</label> <input type=\"text\" id=\"title\"\n");
      out.write("\t\t\t\t\tname=\"title\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"account\">公司账号</label> <input type=\"text\" id=\"account\"\n");
      out.write("\t\t\t\t\tname=\"account\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"bank\">开户行</label> <input type=\"text\" id=\"bank\"\n");
      out.write("\t\t\t\t\tname=\"bank\" style=\"height: 15px;\" />\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<button id=\"y-edit-btn\" type=\"button\">Apply</button>\n");
      out.write("\t\t\t\t<button id=\"n-edit-btn\" type=\"button\">Cancel</button>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\n");
      out.write("\t<script src=\"http://code.jquery.com/ui/1.10.3/jquery-ui.js\"></script>\n");
      out.write("\t<script src=\"static/js/global.js\"></script>\n");
      out.write("\t<script src=\"static/js/index.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
